/**
 * Naye's Picks — AI-generated weekly picks
 * Refreshes every Friday at 0:00 AM
 * Covers events in the next calendar week from moment of refresh
 * All picks: 90%+ confidence only
 */

export interface NayePick {
  sport: string
  homeTeam: string
  awayTeam: string
  league: string
  matchDate: string
  prediction: string
  confidence: number
  odds: number
  tier: 'optimal' | 'high'
  reasoning: string
}

/**
 * Get the current Friday-anchored week's picks.
 * In production, this would be generated by AI on Friday at 0:00 AM
 * and stored in the database. For now, returns seeded AI picks.
 */
export function getNayesPicks(): NayePick[] {
  // Get the seed based on current week (changes every Friday)
  const weekSeed = getCurrentWeekSeed()
  return generatePicksForWeek(weekSeed)
}

/**
 * Returns a seed number that changes every Friday at 0:00 AM.
 * This ensures the same picks are shown for the full week.
 */
function getCurrentWeekSeed(): number {
  const now = new Date()
  // Find last Friday (or today if Friday)
  const day = now.getDay() // 0=Sun, 5=Fri
  const daysToLastFriday = day >= 5 ? day - 5 : day + 2
  const lastFriday = new Date(now)
  lastFriday.setDate(now.getDate() - daysToLastFriday)
  lastFriday.setHours(0, 0, 0, 0)
  // Use week number as seed
  return Math.floor(lastFriday.getTime() / (7 * 24 * 60 * 60 * 1000))
}

/**
 * Get the next Friday's date formatted for display
 */
export function getNextFriday(): string {
  const now = new Date()
  const day = now.getDay()
  const daysUntilFriday = day === 5 ? 7 : (5 - day + 7) % 7 || 7
  const nextFriday = new Date(now)
  nextFriday.setDate(now.getDate() + daysUntilFriday)
  return nextFriday.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
}

/**
 * Get the week range string for the current picks window
 */
export function getWeekRange(): string {
  const now = new Date()
  const day = now.getDay()
  // Week starts from last Friday
  const daysToLastFriday = day >= 5 ? day - 5 : day + 2
  const startDate = new Date(now)
  startDate.setDate(now.getDate() - daysToLastFriday)

  const endDate = new Date(startDate)
  endDate.setDate(startDate.getDate() + 6)

  const fmt = (d: Date) => d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
  return `${fmt(startDate)} – ${fmt(endDate)}`
}

/**
 * Generate deterministic picks based on week seed.
 * In production this would be live AI inference on Friday morning.
 */
function generatePicksForWeek(seed: number): NayePick[] {
  // Rotating pool of AI-generated picks across multiple sports
  const allPicks: NayePick[] = [
    // ⚽ FOOTBALL
    {
      sport: 'Football',
      homeTeam: 'Manchester City',
      awayTeam: 'Chelsea',
      league: 'Premier League',
      matchDate: getMatchDate(1),
      prediction: '1',
      confidence: 94,
      odds: 1.72,
      tier: 'optimal',
      reasoning: 'Man City have won 8 of their last 10 home games. Chelsea are in poor away form — 1 win in 6. Haaland at full fitness and City\'s press dominates possession-light sides. Expected Value strongly positive at these odds.',
    },
    {
      sport: 'Football',
      homeTeam: 'Real Madrid',
      awayTeam: 'Atletico Madrid',
      league: 'La Liga',
      matchDate: getMatchDate(2),
      prediction: 'GG',
      confidence: 91,
      odds: 1.85,
      tier: 'optimal',
      reasoning: 'Both teams to score has landed in 7 of the last 9 Madrid derbies. Atletico have scored in their last 8 away matches. Madrid\'s high press creates space for counter-attacks — goals at both ends highly likely.',
    },
    {
      sport: 'Football',
      homeTeam: 'Bayern Munich',
      awayTeam: 'Borussia Dortmund',
      league: 'Bundesliga',
      matchDate: getMatchDate(3),
      prediction: 'O2.5',
      confidence: 92,
      odds: 1.60,
      tier: 'optimal',
      reasoning: 'Der Klassiker averages 3.8 goals over the last 10 meetings. Both teams top 3 in league for goals scored. Bayern\'s high defensive line is consistently exploited at pace. Historical data: 90% of recent fixtures hit O2.5.',
    },
    // 🏀 BASKETBALL
    {
      sport: 'Basketball',
      homeTeam: 'Los Angeles Lakers',
      awayTeam: 'Golden State Warriors',
      league: 'NBA',
      matchDate: getMatchDate(1),
      prediction: 'O220.5',
      confidence: 93,
      odds: 1.88,
      tier: 'optimal',
      reasoning: 'Both teams rank top-5 in offensive pace this season. Head-to-head: 9 of last 12 meetings exceeded 220 points. Warriors are 3rd fastest-paced team in the league. Pace-vs-pace matchups consistently produce over results.',
    },
    {
      sport: 'Basketball',
      homeTeam: 'Boston Celtics',
      awayTeam: 'Miami Heat',
      league: 'NBA',
      matchDate: getMatchDate(4),
      prediction: 'CEL -5.5',
      confidence: 90,
      odds: 1.90,
      tier: 'high',
      reasoning: 'Celtics are 11-3 ATS at home this season. Miami missing two starters to injury. Boston\'s defensive rating at home (97.4) is the league\'s best. This spread is likely to be covered by halftime.',
    },
    // 🎾 TENNIS
    {
      sport: 'Tennis',
      homeTeam: 'Novak Djokovic',
      awayTeam: 'Carlos Alcaraz',
      league: 'ATP Masters',
      matchDate: getMatchDate(2),
      prediction: 'DJOK WIN',
      confidence: 91,
      odds: 2.10,
      tier: 'optimal',
      reasoning: 'Djokovic is 7-2 against Alcaraz on hard courts. He won their last 3 meetings at Masters level. Alcaraz has shown vulnerability in second sets when pushed to a 3-setter. Djokovic\'s serve holds at 85% on this surface.',
    },
    {
      sport: 'Tennis',
      homeTeam: 'Iga Swiatek',
      awayTeam: 'Aryna Sabalenka',
      league: 'WTA Finals',
      matchDate: getMatchDate(3),
      prediction: 'SWI WIN',
      confidence: 90,
      odds: 1.75,
      tier: 'high',
      reasoning: 'Swiatek leads the H2H 8-5 overall and 5-2 on hard courts in the last 2 years. Her return game disrupts Sabalenka\'s first-serve pattern. At this price, positive expected value is clear.',
    },
    // 🏈 AMERICAN FOOTBALL
    {
      sport: 'American Football',
      homeTeam: 'Kansas City Chiefs',
      awayTeam: 'Dallas Cowboys',
      league: 'NFL',
      matchDate: getMatchDate(5),
      prediction: 'KC -3',
      confidence: 92,
      odds: 1.91,
      tier: 'optimal',
      reasoning: 'Chiefs are 9-2 ATS as home favorites under Mahomes. Dallas secondary ranks 28th in pass yards allowed. KC\'s red zone efficiency (68%) is the league\'s highest. Spot as small fav is historically very profitable for this franchise.',
    },
    // ⚾ BASEBALL
    {
      sport: 'Baseball',
      homeTeam: 'New York Yankees',
      awayTeam: 'Houston Astros',
      league: 'MLB',
      matchDate: getMatchDate(4),
      prediction: 'U8',
      confidence: 90,
      odds: 1.87,
      tier: 'high',
      reasoning: 'Both starting pitchers rank top-10 in ERA this season. The Astros have gone under in 7 of their last 10 road games. Yankees\' bullpen ERA at home is 2.89. Pitcher\'s duel expected — under is the play.',
    },
    // 🏒 HOCKEY
    {
      sport: 'Hockey',
      homeTeam: 'Colorado Avalanche',
      awayTeam: 'Tampa Bay Lightning',
      league: 'NHL',
      matchDate: getMatchDate(6),
      prediction: 'COL ML',
      confidence: 91,
      odds: 1.80,
      tier: 'optimal',
      reasoning: 'Colorado have won 8 straight home games. Tampa are 2-7 in their last 9 road trips. Makar is healthy and averaging 1.4 points per game this month. Home ice advantage is maximized with this matchup.',
    },
  ]

  // Select 8 picks based on the week seed (different picks each week)
  const shuffled = seededShuffle(allPicks, seed)
  return shuffled.slice(0, 8)
}

function getMatchDate(daysAhead: number): string {
  const date = new Date()
  date.setDate(date.getDate() + daysAhead)
  return date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
}

/**
 * Seeded shuffle — deterministic based on seed value
 */
function seededShuffle<T>(arr: T[], seed: number): T[] {
  const shuffled = [...arr]
  let s = seed
  for (let i = shuffled.length - 1; i > 0; i--) {
    s = (s * 1103515245 + 12345) & 0x7fffffff
    const j = s % (i + 1);
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}
