services:
  - type: web
    name: whinkpredict
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --build-from-source && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_NAME
        value: WhinkPredict
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: /tmp/whinkpredict.db
      - key: NEXT_PUBLIC_APP_URL
        value: https://whinkpredict.onrender.com
